print("Hello Leetcode")
print("Namste Leetcode!")
print("The python programming!!")
print("The SQL ")
print("The Leetcode")
print("Nothing")
print("The commit")
print("This repo has include all type of questions which have Leetcode Problems!")
print("---------------------------")
print("Exam")
print("9 may 2026 Cloud Computing")
print("13 may 2026 DWDM")
print("---------------------------")
