print("The commit")
print("This repo has include all type of questions which have Leetcode Problems!")
print("All type Questions")
print("Leetcode")
print("SQL")
print("start Aiml")
print("AI")
print("Java Fundamental")
print("oops concept s")
print("Java Basic")
print("Java OOP's")
print("Play Bold")
