print("hello leetcode")
print("Namste SQL")
print("Namste Python")
print("Namste Suyash ")
print("Namaste duniya")
print(97)
print(717003)
print(01112003)
print()
print("Hello Suyxcode")
print("namste python")
print("Namste Sql")
